import initTranslations from "@/i18n/i18n";
import Link from "next/link";

const i18nNamespaces = ["home"];

export const metadata = {
  title: "PubStar",
  description: "Generated by create next app",
};

export default async function Home({ params: { locale } }) {
  const { t } = await initTranslations(locale, i18nNamespaces);

  return (
    <main>
      <h1 className="text-3xl font-bold underline">{t("home")}</h1>
      <Link href={`/admin`}>Admin</Link>
    </main>
  );
}
